### ISSUE TITLE
Possible roadmap for activity in thie repo

### ISSUE THREAD

**Issue by kltm** [deepakunni3/golr-schema-generator#5]
The following things could be done here to help move the activity in this repo towards the GO roadmap.

- [ ] Multi-input CLI functionality
- [ ] Output compatibility with current OWLTools
- [ ] Output compatibility with Solr...8 now?

Outside this repo, for testing, we may need:
- [ ] owltools version with SolrJ running with something that work with Solr 8 so that we can test
- [ ] after that, we have a base to start checking what changes clients need for the change (if any)...
